services:
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - "8075:8075"  
      - "50000:50000"
    container_name: jenkins-server
    environment:
      - JENKINS_OPTS=--httpPort=8075 
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins-net

networks:
  jenkins-net:
    driver: bridge